se redacto manual de sistema
capitalexpress/capitalexpress.github.io pull request #5
Opened 2024-06-18 21:26 UTC by catalinapinillas

## Describe the PR content and subject

Se redactó manual de Sistemas abarcando factoring (facturas y documentos) y dejando de manera inconclusa Quazar, se afinaron detalles de redacción, títulos, encabezados y formatos de imágen.
## Proof of completion
 
![image](https://github.com/capitalexpress/capitalexpress.github.io/assets/173074083/858d8821-4023-41cb-b018-bf862a6a0e0a)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Not bug related code refactor

## Checklisk
 
- [x]  Ensure the code follows the project's coding standards
    - [x]  Choose descriptive and unambiguous names.
    - [x]  Make meaningful distinctions.
    - [x]  Use pronounceable names.
    - [x]  Use searchable names.
    - [x]  Replace magic numbers with named constants. (Also magic text)
    - [x]  Avoid encodings. Don’t append prefixes or type information.
- [x]  Check if the new code has proper unit tests
- [x]  Verify that the code is properly commented for understandability
    - [x]  Remove poor quality, not meaningful comments
    - [x]  Use comments on non standard code and hard
- [x]  Check if the code changes are relevant to the pull request description
- [x]  Ensure the new code does not introduce any new bugs
- [x]  Check if the pull request contains minimal and logical commits
- [x]  Check if the code changes affect performance and suggest improvements if it does
- [ ]  Review if the pull request resolves the issue it is linked to
    - [x]  If not, describe why the PR y needed/split.  Quedaró pendiente la redacción de Clientes y matriz de riesgo, además de correcciones de formato, tipeo y terminar la sección de Quazar.
- [x]  Do not include extensive refactoring if not requested
- [x]  Ensure all continuous integration checks are passed
- [x]  Provide proof of completion on issue or pull request

2024-06-18 22:01 UTC, dquinteros requested changes

2024-06-18 22:01 UTC, dquinteros commented on _posts/2024-06-04-factoring-documentos.md
> +*Aquí puedes ver la columna mencionada*
Colocar la referencia a la imagen por encima de la imagen.

2024-06-18 22:01 UTC, dquinteros commented on _posts/2024-06-05-factoring-documento-vigente.md
> +title: ¿Quieres saber si el documento que buscas esta vigente?, aqui te indicamos como.
```suggestion
title: ¿Quieres saber si el documento que buscas esta vigente?, aquí te indicamos como.
```

2024-06-18 22:01 UTC, dquinteros commented on _posts/2024-06-06-factoring-documentos-mora.md
Mezclar este pors con el de vigente.

2024-06-19 13:39 UTC, catalinapinillas commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +title: Filtra la información en pantalla y  sintetizar los resultados.
listo

2024-06-19 13:42 UTC, catalinapinillas commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +Con esto podrás ver la información solo de ese Deudor, además junto con eso podrás seleccionar las columnas que quieres que se visualicen, eliminando las que no tienen información relevante para el c
listo :)

2024-06-19 13:43 UTC, catalinapinillas commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +tags: [facturas, comercial, burcar, filtro]
listo :)

2024-06-19 13:44 UTC, catalinapinillas commented on _posts/2024-06-03-factoring-facturas-rango.md
> +tags: [facturas, comercial, burcar, filtro, compra]
listo :)

2024-06-19 13:54 UTC, catalinapinillas commented on _posts/2024-06-05-factoring-documento-vigente.md
> +title: ¿Quieres saber si el documento que buscas esta vigente?, aqui te indicamos como.
listo :)

2024-06-19 15:08 UTC, catalinapinillas commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +Con  los filtros que necesitas consultar activos podrás ver la información precisa que estas buscando sin datos que te interrumpan en tu negocio.
Listo :)

2024-06-19 15:20 UTC, dquinteros requested changes

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-01-factoring-facturas-seleccion.md
> + *aquí un ejemplo*
Aún no resuelto

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +Junto con los filtros de Cliente, Ejecutivo, Rango de fecha y Folio, cuentas con la opción de filtrar por *Deudor*.
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-03-factoring-facturas-rango.md
> +title: Acitva Rangos de fecha y el filtro CRM para ver que facturas podemos comprar.
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-03-factoring-facturas-rango.md
> +tags: [facturas, comercial, buscar, filtro, ventas, compras búsqueda]
```suggestion
tags: [facturas, comercial, buscar, filtro, ventas, compras, búsqueda]
```

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-03-factoring-facturas-rango.md
> +Podrás notar que el listado se filtró, junto con esto debes activar el switch de Crm para que asi veas reflejadas solo las facturas que pueden ser compradas por **Capital Express Servicios Financiero
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-04-factoring-documentos.md
> +title: Quieres ver los documentos que han sido adquiridos por Capital Express Servicios Financieros, ingresa de esta forma.
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-04-factoring-documentos.md
> +Para navegar en este apartado contaras con los filtros de Cliente, Ejecutivo, Rango de fecha y folio. Nos encontraremos con todos los Documentos que han sido adquiridos por **Capital Express Servicio
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-04-factoring-documentos.md
> +También contaremos con un filtrado de estado, que ayudará a ver si el documento se encuentra Vigente, Moroso, Cancelado, etc. Para tener una visión de como proceder con cada caso.
cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-05-factoring-documento-vigente.md
> +Según el Cliente al cual quieres buscar, es aconsejable que indiques un periodo de fechas en el cual estas realizando la consulta, aplica la mayor cantidad de filtros en la parte superior para que la
Cambio no aplicado

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-07-factoring-quazar-cyv-fitros.md
> +</p>
Quiza es mejor colocar esta imagenes lado a lado en luega de una encima de la otra

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-08-factoring-quazar-competencia.md
> +title: Necesitas ver como trabaja tu Cliete con los otros Factoring, te indicaremos como.
```suggestion
title: ¿Quieres evaluar tu competencia¿, te indicaremos como.
```

2024-06-19 15:20 UTC, dquinteros commented on _posts/2024-06-08-factoring-quazar-competencia.md
> +Se mostrán dos tablas donde verás el detalle de como el Cliente ha operado con los distintos Factoring a los que ha acudido, en la superior verás el porcentaje y los montos de facturas que cada Facto
```suggestion
Se muestran dos tablas donde verás el detalle de las opreaciones de tus clientes con los distintos Factoring a los que ha acudido, en la superior verás el porcentaje y los montos de facturas que cada Factoring ha adquirido al Cliente y el desglose del total de facturas cedidas por mes.
```

2024-06-19 16:28 UTC, catalinapinillas commented on _posts/2024-06-06-quasar-comprayventa.md
> +subtitle: Quazar Compras, ventas y Factorizacion.
Listo :)

2024-06-19 16:33 UTC, catalinapinillas commented on _posts/2024-06-02-factoring-facturas-filtros.md
> +Junto con los filtros de Cliente, Ejecutivo, Rango de fecha y Folio, cuentas con la opción de filtrar por *Deudor*.
creo que ahora fue aplicado

2024-06-19 16:38 UTC, catalinapinillas commented on _posts/2024-06-03-factoring-facturas-rango.md
> +tags: [facturas, comercial, buscar, filtro, ventas, compras búsqueda]
listo

2024-06-19 16:40 UTC, catalinapinillas commented on _posts/2024-06-04-factoring-documentos.md
> +title: Quieres ver los documentos que han sido adquiridos por Capital Express Servicios Financieros, ingresa de esta forma.
listo

2024-06-19 16:42 UTC, catalinapinillas commented on _posts/2024-06-03-factoring-facturas-rango.md
> +Podrás notar que el listado se filtró, junto con esto debes activar el switch de Crm para que asi veas reflejadas solo las facturas que pueden ser compradas por **Capital Express Servicios Financiero
listo :)

2024-06-19 16:42 UTC, catalinapinillas commented on _posts/2024-06-04-factoring-documentos.md
> +Para navegar en este apartado contaras con los filtros de Cliente, Ejecutivo, Rango de fecha y folio. Nos encontraremos con todos los Documentos que han sido adquiridos por **Capital Express Servicio
listo

2024-06-19 16:45 UTC, catalinapinillas commented on _posts/2024-06-05-factoring-documento-vigente.md
> +Según el Cliente al cual quieres buscar, es aconsejable que indiques un periodo de fechas en el cual estas realizando la consulta, aplica la mayor cantidad de filtros en la parte superior para que la
listo :)

2024-06-19 16:46 UTC, catalinapinillas commented on _posts/2024-06-07-factoring-quazar-cyv-fitros.md
> +subtitle: Quazar - Compras, ventas y Factorizacion filtros
listo :)

2024-06-19 16:48 UTC, catalinapinillas commented on _posts/2024-06-08-factoring-quazar-competencia.md
> +title: Necesitas ver como trabaja tu Cliete con los otros Factoring, te indicaremos como.
listo

2024-06-19 16:48 UTC, catalinapinillas commented on _posts/2024-06-08-factoring-quazar-competencia.md
> +Se mostrán dos tablas donde verás el detalle de como el Cliente ha operado con los distintos Factoring a los que ha acudido, en la superior verás el porcentaje y los montos de facturas que cada Facto
listo

2024-06-19 16:49 UTC, catalinapinillas commented on _posts/2024-06-06-quasar-comprayventa.md
> +En la parte inferior veras el detalle de la tabla de superior, pero separada por periodos, estos estaran separados por rangos de los días del mes y los que a su vez se encontrarán separados por los m
listo

2024-06-19 16:51 UTC, catalinapinillas commented on _posts/2024-06-05-factoring-documento-vigente.md
> +Ten los datos básicos para iniciar una busqueda como nombre del Cliente y rango de fecha, recuerda que meintras más datos ingreses más acotados serán los resultados. Seguido de eso en *Filtrar por es
listo

2024-06-19 20:24 UTC, catalinapinillas commented on _posts/2024-06-07-factoring-quazar-cyv-fitros.md
> +</p>
listo, gracias por tu ayuda 
![PATITTA DE GATO](https://github.com/capitalexpress/capitalexpress.github.io/assets/173074083/17ba6a1e-cb99-47e3-bfc2-f167320d9ee1)

2024-06-19 22:39 UTC, catalinapinillas commented on _posts/2024-06-05-factoring-documento-vigente.md
> +Haciendo estos pasos podrás ver los documentos vigentes que tiene el Cliente seleccionado en estos momentos y en el periodo de tiempo seleccionado.
listo

2024-06-19 22:40 UTC, catalinapinillas commented on _posts/2024-06-01-factoring-facturas-seleccion.md
> + *aquí un ejemplo*
listo

2024-06-19 22:41 UTC, dquinteros commented on _posts/2024-06-06-quasar-comprayventa.md
> +tags: [quazar, comercial, riesgo, factoring]
```suggestion
tags: [comercial, riesgo, factoring]
```

2024-06-19 22:41 UTC, catalinapinillas commented on _posts/2024-06-18-factoring-quazar-cyv-fitros.md
listo

2024-06-19 22:41 UTC, catalinapinillas commented on _posts/2024-06-18-quasar-comprayventa.md
> +## Aquí podrás ver los detalles de compra y venta de los documentos según tus Clientes.
listo

2024-06-19 22:41 UTC, catalinapinillas commented on _posts/2024-06-18-quasar-comprayventa.md
> +Para comenzar debes seleccionar los filtros básicos para poder realizar una consulta, Cliente y Rango de fecha para que comience a arrojar resultados, sin esto no obtendremos información en la pantal
listo

2024-06-19 22:41 UTC, dquinteros commented on _posts/2024-06-07-factoring-quazar-cyv-fitros.md
> +tags: [quazar, comercial, riesgo, factoring, filtros]
```suggestion
tags: [comercial, riesgo, factoring, filtros]
```

2024-06-19 22:42 UTC, catalinapinillas commented on _posts/2024-06-07-factoring-quazar-cyv-fitros.md
> +tags: [quazar, comercial, riesgo, factoring, filtros]
listo

2024-06-19 22:43 UTC, catalinapinillas commented on _posts/2024-06-06-quasar-comprayventa.md
> +tags: [quazar, comercial, riesgo, factoring]
listo

2024-06-19 22:43 UTC, dquinteros approved these changes

2024-06-19 22:44 UTC, merged

2024-06-21 13:27 UTC, catalinapinillas commented on _posts/2024-06-03-factoring-facturas-rango.md
> +Así estarás seguro que los docuemntos en el listado son los que se pueden adquirir.
listo

2024-06-21 13:32 UTC, catalinapinillas commented on _posts/2024-06-04-factoring-documentos.md
> +*Aquí puedes ver la columna mencionada*
listo

2024-06-21 13:33 UTC, catalinapinillas commented on _posts/2024-06-06-factoring-documentos-mora.md
listo